### ISSUE TITLE
java.io.EOFException

### ISSUE THREAD

**Issue by jakub-zawislak** [magJ/dagor-archive#1]
I'm new to java (php "programmer" here) and I want to run this code. In NetBeans 8.0.2 after run ExtractGui.java, select .bin file and click extract button, I've got exception:

Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Java heap space

Then I tried to change size of space to 2 GB, but still doesn't work:

mar 21, 2015 9:46:47 PM dagor.archive.DagorArchiveReader <init>
INFO: Opening archive: C:\Users\Jakub\Desktop\ussr_kv_1_l_11.dxp.bin
mar 21, 2015 9:46:47 PM dagor.archive.DagorArchiveReader <init>
INFO: Archive is not zlib deflated.
mar 21, 2015 9:46:47 PM dagor.archive.DagorArchiveReader <init>
INFO: Archive contains 15 files.
mar 21, 2015 9:46:47 PM dagor.archive.DagorArchiveReader extract
INFO: Extracting File: kv_1_1939_l_11_body_ao\* to C:\Users\Jakub\Desktop\kv_1_1939_l_11_body_ao\* with size of 827611204 bytes.
java.io.EOFException

What am I doing wrong?

**Comment by magJ** [comment]
Sorry its taken so long to respond, looks like a bug, it shouldn't be running out of memory.
Im guessing that file is from warthunder?, I will try extracting it myself later and see if i get the same result.

**Comment by magJ** [comment]
Sorry I don't support dxp.bin files at the moment, you should try this tool:
http://www.nexusmods.com/warthunder/mods/617/?
